
# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Kyle Galloway
description:      'IT Graduate'
url:              https://www.kylegalloway.co.uk
baseurl:          https://www.kylegalloway.co.uk

author:
  name:           'Kyle Galloway'
  url:


paginate:         5
paginate_path: /Posts/post:num
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Permalinks
permalink:           pretty

# Setup
title:               Kyle Galloway
tagline:             IT Graduate
url:                 https://www.kylegalloway.co.uk
ppaginate:         5
paginate_path: /Posts/post:num
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kyle Galloway
  url:
  email:

# Custom vars

collections:
  projects:
    output: true

page_trailer_title: Hyde
page_trailer_tagline: A Jekyll Theme
version:             2.0.0
github:
  repo:              https://github.com/poole/hyde

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
